Add retention argument to view in graphana script
puppetlabs/puppet-metrics-viewer pull request #11
Opened 2017-06-06 21:42 UTC by npwalker

Prior to this commit, the view in graphana script would load
all data privided in a metrics tarball.  Turns out if you have a
full 90 days of metrics and numerous compile masters this can take
a really long time to load ( sometimes it just hangs in the middle
too ).

After this commit, the view in graphana script defaults to only
loading 30 days of data and can be changed by passing a second
argument to the script that is the number of days to load.

2017-06-06 22:14 UTC, jarretlavallee requested changes

2017-06-06 22:14 UTC, jarretlavallee commented on view-in-grafana.sh
>  usage()
Please update the usage to reflect the new parameter

2017-06-07 22:50 UTC, npwalker commented on view-in-grafana.sh
>  usage()
done... I think

2017-06-07 22:52 UTC, jarretlavallee approved these changes
👍 Looks good

2017-06-07 23:00 UTC, merged