influxdb functionality added
puppetlabs/puppet-metrics-viewer pull request #18
Opened 2017-08-09 23:20 UTC by snghshb

-updated ruby script for using influxdb
-added tag parser for influxdb
-added option to select influxdb database
-8086 port added for @socket

2017-08-10 15:30 UTC, npwalker commented
Seems like we'd need to rename the script if it's going to handle more than graphite now?

We should probably merge in https://github.com/puppetlabs/puppet-metrics-viewer/pull/17 and rebase this onto it.  You'll have to update your code to allow setting the port.

2017-08-10 15:30 UTC, npwalker commented on json2graphite.rb
> +      puts "8086"
this should probably be removed.

2017-08-12 00:03 UTC, Sharpie commented
#17 might not be relevant to these changes unless InfluxDB can accept line protocol input directly over a socket. So far it looks like a HTTP POST is required --- to set the target database and units for the timestamps.

2017-08-12 00:12 UTC, Sharpie requested changes

2017-08-12 00:12 UTC, Sharpie commented on json2graphite.rb
> +    #STDERR.puts "#{e.backtrace}"
Should leave this uncommented or leave it out.

2017-08-12 00:12 UTC, Sharpie commented on json2graphite.rb
> +end
Indentation on these last two `end` statements should be fixed.

2017-09-06 19:16 UTC, suckatrash commented
I have a new PR I could submit that would fix most of the issues called out here. Not sure what to do about renaming the script or changing how the port is handled at this point.

https://github.com/suckatrash/puppet-metrics-viewer/commit/e4e5dd93700034b57c6a7ec32fab60e2be224a45

2017-09-15 21:59 UTC, reidmv commented
From a design perspective, ideally we'd split this into two separate scripts. I don't see a benefit to combining them, especially as there's no benefit to supporting two backends and we're likely to just be moving to InfluxDB.

```
json2graphite.rb
json2influxdb.rb
```

2017-09-15 22:07 UTC, npwalker commented
You really think influxdb will be more prevalent at customers than graphite?  IMO one of the benefits of this was that the dashboards could be exported and used with customers piping the data into graphite from the script.  

I've seen far more graphite installs than influxdb installs.  If we can support both then nevermind but idk how to make a dashboard that works for both.

2017-09-15 22:20 UTC, reidmv commented
@npwalker I think that's a side conversation. My main feedback was "Graphite and InfluxDB are different enough we should have different JSON transformation scripts for them. Unix philosophy."

On that side conversation: I would need to have a better sense of how performant InfluxDB is for our use case before having a strong opinion. I know for a fact that Graphite is really shaky for us, unless/until we can find a better way of mass-inserting our data into it. If InfluxDB is BETTER, that's the argument for moving to it. If and only if. Happy to talk more offline.

2017-10-12 17:43 UTC, Sharpie commented
Finally circling back to this after some months of distraction, including a few performance issues where the work done here was especially helpful. I think we should integrate the Influx work alongside Graphite as a single script. The reason being that we have a common JSON format for input and splitting this into two scripts would mean duplicating the code for ingesting and parsing that.

I'll pull the commits here down, add some extensions and submit a new PR with the results.

2017-11-14 23:54 UTC, Sharpie commented
Closing this out in favor of PR #21 which includes these patches plus some additional changes.

2017-11-14 23:54 UTC, closed without merging