Changing to untar gzip files rather than bzip2
puppetlabs/puppet-metrics-viewer pull request #19
Opened 2017-10-18 19:53 UTC by abottchen

Needed for compatibility with 
https://github.com/npwalker/pe_metric_curl_cron_jobs/pull/45

2017-10-18 19:56 UTC, npwalker commented on view-in-grafana.sh
> +find "$datadir" -type f -ctime -$RETENTION_DAYS -iname "*.bz2" -exec bash -c 'tar zxf "{}" -C $(dirname "{}")' \; 2>/dev/null;
isn't the find still looking for .bz2 files?

2017-10-18 19:59 UTC, abottchen commented on view-in-grafana.sh
> +find "$datadir" -type f -ctime -$RETENTION_DAYS -iname "*.bz2" -exec bash -c 'tar zxf "{}" -C $(dirname "{}")' \; 2>/dev/null;
Yep.  That was dumb.

2017-10-18 20:00 UTC, npwalker commented on view-in-grafana.sh
> +find "$datadir" -type f -ctime -$RETENTION_DAYS -iname "*.gz" -exec bash -c 'tar xf "{}" -C $(dirname "{}")' \; 2>/dev/null;
We probably shouldn't replace this though right?  We should just unzip files in either format so we should leave the bz2 line and add the gz line?

2017-10-18 20:01 UTC, npwalker requested changes
Also, squash your commits :)

2018-01-18 19:07 UTC, npwalker approved these changes

2018-01-18 19:08 UTC, npwalker commented
@abottchen did you actually test this?

2018-01-19 00:09 UTC, abottchen commented
@npwalker Yea.  It works for me with gz files and with a mixture of gz and bz2 files using this code.

2018-01-19 00:26 UTC, merged